# Generated by Django 5.2.1 on 2025-05-21 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_razao_social", models.CharField(max_length=255)),
                (
                    "nome_fantasia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[("publico", "Público"), ("privado", "Privado")],
                        max_length=10,
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("fisica", "Física"), ("juridica", "Jurídica")],
                        max_length=10,
                    ),
                ),
                ("cnpj_cpf", models.CharField(max_length=18, unique=True)),
                (
                    "natureza_juridica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "inscricao_municipal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("endereco", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=10)),
                ("pais", models.CharField(default="Brasil", max_length=50)),
                ("nome_responsavel", models.CharField(max_length=100)),
                ("cargo_responsavel", models.CharField(max_length=100)),
                ("telefone_contato", models.CharField(max_length=20)),
                ("email_contato", models.EmailField(max_length=254)),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("produto", "Produto"),
                            ("servico", "Serviço"),
                            ("treinamento", "Treinamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("unidade", models.CharField(max_length=50)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_contrato", models.CharField(max_length=100, unique=True)),
                (
                    "ata_registro_preco",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pregao_eletronico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("processo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "termo_referencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vigencia",
                    models.IntegerField(
                        choices=[(12, "12 meses"), (24, "24 meses"), (36, "36 meses")]
                    ),
                ),
                ("data_assinatura", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.cliente",
                    ),
                ),
                ("fornecedores", models.ManyToManyField(to="contracts.itemfornecedor")),
            ],
        ),
        migrations.CreateModel(
            name="ItemContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_item", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("solucao", "Solução"),
                            ("servico", "Serviço"),
                            ("treinamento", "Treinamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unidade", models.CharField(max_length=50)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "vigencia_produto",
                    models.IntegerField(
                        blank=True,
                        choices=[(12, "12 meses"), (24, "24 meses"), (36, "36 meses")],
                        null=True,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="contracts.contrato",
                    ),
                ),
            ],
            options={
                "unique_together": {("contrato", "numero_item")},
            },
        ),
        migrations.CreateModel(
            name="OrdemFornecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("numero_cliente", models.CharField(max_length=100)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("execucao", "Em execução"),
                            ("finalizada", "Finalizada"),
                            ("faturada", "Faturada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_ativacao", models.DateField(blank=True, null=True)),
                ("data_faturamento", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.contrato",
                    ),
                ),
                (
                    "item_contrato",
                    models.ForeignKey(
                        limit_choices_to={
                            "tipo__in": ["hardware", "software", "solucao"]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.itemcontrato",
                    ),
                ),
                (
                    "item_fornecedor",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "produto"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.itemfornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Fornecimento",
                "verbose_name_plural": "Ordens de Fornecimento",
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                (
                    "gerente_projeto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consultor_tecnico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("execucao", "Em execução"),
                            ("finalizada", "Finalizada"),
                            ("faturada", "Faturada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_emissao_trd", models.DateField(blank=True, null=True)),
                ("data_faturamento", models.DateField(blank=True, null=True)),
                ("horas_gerente", models.PositiveIntegerField(default=0)),
                ("horas_tecnico", models.PositiveIntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.contrato",
                    ),
                ),
                (
                    "item_contrato",
                    models.ForeignKey(
                        limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.itemcontrato",
                    ),
                ),
                (
                    "item_fornecedor",
                    models.ForeignKey(
                        limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.itemfornecedor",
                    ),
                ),
            ],
        ),
    ]
