# Generated by Django 5.2.1 on 2025-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contrato_situacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemfornecimento",
            name="valor_faturado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="valor_faturado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
