# Generated by Django 5.2.1 on 2025-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_ordemfornecimento_valor_faturado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("import", "Importação"), ("export", "Exportação")],
                        max_length=10,
                    ),
                ),
                ("arquivo", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Sucesso"), ("error", "Erro")],
                        max_length=10,
                    ),
                ),
                ("mensagem", models.TextField()),
            ],
        ),
    ]
