# Generated by Django 5.2.1 on 2025-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_importexportlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemfornecedor",
            name="nome",
        ),
        migrations.AddField(
            model_name="itemfornecedor",
            name="fornecedor",
            field=models.CharField(
                choices=[
                    ("iB Services", "iB Services"),
                    ("MVC Security", "MVC Security"),
                    ("Red Hat", "Red Hat"),
                    ("CyberArk", "CyberArk"),
                    ("Trend Micro", "Trend Micro"),
                    ("Fortinet", "Fortinet"),
                    ("Ridge Security", "Ridge Security"),
                    ("Thales", "Thales"),
                    ("Viewtinet", "Viewtinet"),
                    ("Outro Fornecedor", "Outro Fornecedor"),
                ],
                default="iB Services",
                max_length=100,
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="itemfornecedor",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemfornecedor",
            name="outro_fornecedor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
