# Generated by Django 5.2.1 on 2025-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0005_remove_itemfornecedor_nome_itemfornecedor_fornecedor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrato",
            name="fornecedores",
        ),
        migrations.AddField(
            model_name="contrato",
            name="fornecedores",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
