# Generated by Django 5.2.1 on 2025-05-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_remove_contrato_fornecedores_contrato_fornecedores"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="valor_global",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="ata_registro_preco",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ARP"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="contracts.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_assinatura",
            field=models.DateField(verbose_name="Data de Assinatura"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_fim",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="fornecedores",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Fornecedores"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_contrato",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Número do Contrato"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="pregao_eletronico",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pregão Eletrônico"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="processo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Processo"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="situacao",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="termo_referencia",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Termo de Referência (TR)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="vigencia",
            field=models.IntegerField(
                choices=[(12, "12 meses"), (24, "24 meses"), (36, "36 meses")],
                verbose_name="Vigência (meses)",
            ),
        ),
    ]
