# Generated by Django 5.2.1 on 2025-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_contrato_valor_global_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcontrato",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="numero_item",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Hardware", "Hardware"),
                    ("Software", "Software"),
                    ("Solução", "Solução"),
                    ("Serviço", "Serviço"),
                    ("Treinamento", "Treinamento"),
                ],
                max_length=20,
            ),
        ),
    ]
