# Generated by Django 5.2.1 on 2025-05-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_itemcontrato_valor_total_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordemservico",
            old_name="numero",
            new_name="numero_os",
        ),
        migrations.AlterUniqueTogether(
            name="ordemservico",
            unique_together={("numero_os", "contrato")},
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="data_termino",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="gerente_projetos",
            field=models.CharField(default="Gerente Não Informado", max_length=100),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="hora_inicio",
            field=models.TimeField(default="09:00:00"),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="hora_termino",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="horas_consultor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="horas_totais",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="numero_os_cliente",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="tipo_os",
            field=models.CharField(default="Serviço", editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="unidade",
            field=models.CharField(default="Horas", editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="consultor_tecnico",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.contrato"
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="data_inicio",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="horas_gerente",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.itemcontrato"
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.itemfornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("execucao", "Em execução"),
                    ("finalizada", "Finalizada"),
                    ("faturada", "Faturada"),
                ],
                default="Aberta",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="data_fim",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="gerente_projeto",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="horas_tecnico",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="valor_faturado",
        ),
    ]
