# Generated by Django 5.2.1 on 2025-05-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_rename_numero_ordemservico_numero_os_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcontrato",
            name="lote",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número do lote (Ex.: 1, 2, 3)",
                verbose_name="Lote",
            ),
        ),
    ]
