# Generated by Django 5.2.1 on 2025-05-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_itemcontrato_lote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemcontrato",
            unique_together={("contrato", "lote", "numero_item")},
        ),
    ]
