# Generated by Django 5.2.1 on 2025-05-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_alter_itemcontrato_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="valor_global",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=14
            ),
        ),
    ]
