# Generated by Django 5.2.1 on 2025-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_alter_contrato_valor_global"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("solucao", "Solução"),
                    ("servico", "Serviço"),
                    ("treinamento", "Treinamento"),
                ],
                max_length=20,
            ),
        ),
    ]
