# Generated by Django 5.2.1 on 2025-05-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_alter_itemcontrato_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contrato",
            options={"verbose_name": "Contrato", "verbose_name_plural": "Contratos"},
        ),
    ]
