# Generated by Django 5.2.1 on 2025-05-26 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0014_alter_contrato_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordemfornecimento",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Ordem de Fornecimento",
                "verbose_name_plural": "Ordens de Fornecimento",
            },
        ),
        migrations.RemoveField(
            model_name="ordemfornecimento",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="ordemfornecimento",
            name="numero_cliente",
        ),
        migrations.RemoveField(
            model_name="ordemfornecimento",
            name="valor_faturado",
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 26, 17, 6, 35, 837971, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="numero_of",
            field=models.CharField(
                default="OF TEMP/2025",
                max_length=20,
                unique=True,
                verbose_name="Número da OF",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="numero_of_cliente",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Número da OF do Cliente",
            ),
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="unidade",
            field=models.CharField(
                default="Licença", max_length=20, verbose_name="Unidade"
            ),
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="valor_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="vigencia_produto",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Vigência do Produto (meses)"
            ),
        ),
        migrations.AlterField(
            model_name="ordemfornecimento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("execucao", "Em execução"),
                    ("finalizada", "Finalizada"),
                    ("faturada", "Faturada"),
                ],
                default="aberta",
                max_length=20,
            ),
        ),
    ]
