# Generated by Django 5.2.1 on 2025-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_alter_ordemfornecimento_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="gerente_projetos",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Gerente de Projetos",
            ),
        ),
    ]
