# Generated by Django 5.2.1 on 2025-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0016_alter_ordemservico_gerente_projetos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="hora_termino",
            field=models.TimeField(default="19:00:00"),
        ),
    ]
