# Generated by Django 5.2.1 on 2025-06-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0017_alter_ordemservico_hora_termino"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemcontrato",
            options={
                "verbose_name": "Item de Contrato",
                "verbose_name_plural": "Itens de Contrato",
            },
        ),
        migrations.AddField(
            model_name="itemcontrato",
            name="saldo_quantidade_inicial",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Saldo Inicial de Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="numero_item",
            field=models.CharField(max_length=50, verbose_name="Número do Item"),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Quantidade Total"
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("solucao", "Solução"),
                    ("servico", "Serviço"),
                    ("treinamento", "Treinamento"),
                ],
                max_length=20,
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="unidade",
            field=models.CharField(max_length=50, verbose_name="Unidade"),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=14,
                verbose_name="Valor Total do Item",
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="vigencia_produto",
            field=models.IntegerField(
                blank=True,
                choices=[(12, "12 meses"), (24, "24 meses"), (36, "36 meses")],
                null=True,
                verbose_name="Vigência do Produto (meses)",
            ),
        ),
    ]
