# Generated by Django 5.2.1 on 2025-11-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0020_alter_ordemservico_numero_os"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Centro de Custo"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único do centro de custo",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaborador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do Lead"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor Estimado (R$)",
                    ),
                ),
                (
                    "probabilidade",
                    models.IntegerField(
                        default=0,
                        help_text="Probabilidade de fechamento (0-100%)",
                        verbose_name="Probabilidade (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("qualificado", "Qualificado"),
                            ("proposta", "Proposta Enviada"),
                            ("negociacao", "Em Negociação"),
                            ("ganho", "Ganho"),
                            ("perdido", "Perdido"),
                        ],
                        default="novo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "data_prevista_fechamento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data Prevista de Fechamento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="contracts.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "gerente_comercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="contracts.colaborador",
                        verbose_name="Gerente Comercial Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Oportunidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="Título da Oportunidade"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "valor_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor Estimado (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospeccao", "Prospecção"),
                            ("qualificacao", "Qualificação"),
                            ("proposta", "Proposta"),
                            ("negociacao", "Negociação"),
                            ("fechado", "Fechado"),
                            ("perdido", "Perdido"),
                        ],
                        default="prospeccao",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_prevista_fechamento",
                    models.DateField(verbose_name="Data Prevista de Fechamento"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oportunidades",
                        to="contracts.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "gerente_comercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oportunidades",
                        to="contracts.colaborador",
                        verbose_name="Gerente Comercial Responsável",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oportunidade",
                        to="contracts.lead",
                        verbose_name="Lead Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidade",
                "verbose_name_plural": "Oportunidades",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Reclamacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="Título da Reclamação"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Problema")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_analise", "Em Análise"),
                            ("em_resolucao", "Em Resolução"),
                            ("resolvida", "Resolvida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "data_abertura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Abertura"
                    ),
                ),
                (
                    "data_resolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Resolução"
                    ),
                ),
                (
                    "solucao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Solução Aplicada"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamacoes",
                        to="contracts.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamacoes",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "gerente_sucessos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamacoes",
                        to="contracts.colaborador",
                        verbose_name="Gerente de Sucessos Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reclamação",
                "verbose_name_plural": "Reclamações",
                "ordering": ["-data_abertura"],
            },
        ),
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do SLA"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("disponibilidade", "Disponibilidade"),
                            ("tempo_resposta", "Tempo de Resposta"),
                            ("resolucao", "Tempo de Resolução"),
                            ("atendimento", "Atendimento"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de SLA",
                    ),
                ),
                (
                    "meta",
                    models.CharField(
                        help_text="Ex: 99.9% de disponibilidade, 4 horas de resposta",
                        max_length=100,
                        verbose_name="Meta",
                    ),
                ),
                (
                    "valor_penalidade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor da Penalidade (R$)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slas",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA",
                "verbose_name_plural": "SLAs",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título da Tarefa"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("pausada", "Pausada"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "data_inicio_prevista",
                    models.DateField(verbose_name="Data de Início Prevista"),
                ),
                (
                    "data_termino_prevista",
                    models.DateField(verbose_name="Data de Término Prevista"),
                ),
                (
                    "data_inicio_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Início Real"
                    ),
                ),
                (
                    "data_termino_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Término Real"
                    ),
                ),
                (
                    "horas_planejadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Horas Planejadas",
                    ),
                ),
                (
                    "horas_consumidas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Calculado automaticamente baseado em lançamentos de horas",
                        max_digits=6,
                        verbose_name="Horas Consumidas",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apenas para tarefas não vinculadas a OS (horas não faturadas)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="contracts.centrocusto",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: vincular a uma OS para horas faturadas",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="contracts.ordemservico",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultor ou Gerente de Projetos",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="contracts.colaborador",
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoHora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_termino", models.TimeField(verbose_name="Hora de Término")),
                (
                    "horas_trabalhadas",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        verbose_name="Horas Trabalhadas",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Trabalho"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos_horas",
                        to="contracts.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos_horas",
                        to="contracts.tarefa",
                        verbose_name="Tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento de Hora",
                "verbose_name_plural": "Lançamentos de Horas",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
    ]
