# Generated by Django 5.2.1 on 2025-11-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0022_add_gerentes_to_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="gerente_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"cargo__icontains": "gerente"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_gerenciados",
                to="contracts.colaborador",
                verbose_name="Gerente do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="horas_planejadas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total de horas planejadas para a OS (soma das horas planejadas das tarefas)",
                max_digits=6,
                verbose_name="Horas Planejadas",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="horas_realizadas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total de horas realizadas (calculado automaticamente das tarefas)",
                max_digits=6,
                verbose_name="Horas Realizadas",
            ),
        ),
    ]
