# Generated by Django 5.2.1 on 2025-11-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0023_contrato_gerente_contrato_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Backlog",
                "verbose_name_plural": "Backlogs",
            },
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="ordem_servico",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: vincular a uma OS para horas faturadas (criada ao fechar sprint)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="contracts.ordemservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="backlog",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarefa no backlog do projeto",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="contracts.backlog",
                verbose_name="Backlog",
            ),
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Projeto"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejamento", "Planejamento"),
                            ("em_andamento", "Em Andamento"),
                            ("pausado", "Pausado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejamento",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim_prevista",
                    models.DateField(verbose_name="Data de Fim Prevista"),
                ),
                (
                    "data_fim_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Fim Real"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "gerente_projeto",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"cargo__icontains": "gerente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_gerenciados",
                        to="contracts.colaborador",
                        verbose_name="Gerente de Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="backlog",
            name="projeto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backlog",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome da Sprint"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("ativa", "Ativa"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="planejada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ordem_servico",
                    models.OneToOneField(
                        blank=True,
                        help_text="OS criada automaticamente ao fechar a sprint",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint",
                        to="contracts.ordemservico",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="contracts.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.AddField(
            model_name="tarefa",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarefa movida para sprint",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas",
                to="contracts.sprint",
                verbose_name="Sprint",
            ),
        ),
    ]
