# Generated by Django 5.2.1 on 2025-11-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0024_add_projeto_backlog_sprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="data_fim_real",
        ),
        migrations.AlterField(
            model_name="projeto",
            name="contrato",
            field=models.OneToOneField(
                help_text="Um projeto para cada contrato",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projeto",
                to="contracts.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="data_fim_prevista",
            field=models.DateField(editable=False, verbose_name="Data de Fim Prevista"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="data_inicio",
            field=models.DateField(editable=False, verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_termino_prevista",
            field=models.DateField(
                help_text="Não pode ser maior que a data de fim da sprint",
                verbose_name="Data de Término Prevista",
            ),
        ),
    ]
