# Generated by Django 5.2.1 on 2025-11-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0025_ajustar_projeto_tarefa_regras"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="status_sprint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nao_iniciada", "Não Iniciada"),
                    ("em_execucao", "Em Execução"),
                    ("finalizada", "Finalizada"),
                ],
                help_text="Status quando a tarefa está em uma sprint",
                max_length=20,
                null=True,
                verbose_name="Status (Sprint)",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="backlog",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarefa no backlog do projeto (alocação automática)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="contracts.backlog",
                verbose_name="Backlog",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="prioridade",
            field=models.CharField(
                choices=[("baixa", "Baixa"), ("media", "Média"), ("alta", "Alta")],
                default="media",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                help_text="Consultor Técnico ou Gerente de Projetos",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas",
                to="contracts.colaborador",
                verbose_name="Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="Nome da Tarefa"),
        ),
    ]
