# Generated by Django 5.2.1 on 2025-11-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0026_adicionar_status_sprint_tarefa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="ordem_servico",
            field=models.OneToOneField(
                blank=True,
                help_text="OS vinculada à sprint (criada automaticamente se não existir)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprint",
                to="contracts.ordemservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
    ]
