# Generated by Django 5.2.1 on 2025-11-23 19:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0027_alter_sprint_ordem_servico"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetoPublico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Denominação do projeto público",
                        max_length=255,
                        verbose_name="Nome do Projeto",
                    ),
                ),
                (
                    "orcamento_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Orçamento total do projeto em R$",
                        max_digits=15,
                        verbose_name="Orçamento Total",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do projeto",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projeto Público",
                "verbose_name_plural": "Projetos Públicos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="centro_custo",
        ),
        migrations.CreateModel(
            name="ContratoPublico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_contrato",
                    models.CharField(
                        help_text="Número oficial do contrato",
                        max_length=100,
                        unique=True,
                        verbose_name="Número do Contrato",
                    ),
                ),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor inicial do contrato em R$",
                        max_digits=15,
                        verbose_name="Valor Inicial",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        help_text="Data de início da vigência do contrato",
                        verbose_name="Data de Início",
                    ),
                ),
                (
                    "vigencia_original_meses",
                    models.IntegerField(
                        help_text="Vigência original do contrato em meses",
                        verbose_name="Vigência Original (meses)",
                    ),
                ),
                (
                    "regime_legal",
                    models.CharField(
                        choices=[
                            ("LEI_14133", "Lei 14.133/2021 (Licitações e Contratos)"),
                            (
                                "LEI_13303",
                                "Lei 13.303/2016 (Estatuto Jurídico da Empresa Pública)",
                            ),
                        ],
                        help_text="Regime legal aplicável ao contrato",
                        max_length=20,
                        verbose_name="Regime Legal",
                    ),
                ),
                (
                    "objeto",
                    models.TextField(
                        help_text="Objeto do contrato", verbose_name="Objeto"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        help_text="Projeto ao qual o contrato está vinculado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="contracts.projetopublico",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato Público",
                "verbose_name_plural": "Contratos Públicos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TermoAditivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_termo",
                    models.CharField(
                        help_text="Número oficial do termo aditivo",
                        max_length=100,
                        verbose_name="Número do Termo Aditivo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRORROGACAO", "Prorrogação"),
                            ("VALOR", "Aditivo de Valor"),
                            ("REEQUILIBRIO", "Reequilíbrio Econômico-Financeiro"),
                        ],
                        help_text="Tipo de termo aditivo",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "meses_acrescimo",
                    models.IntegerField(
                        default=0,
                        help_text="Meses adicionais de vigência (apenas para prorrogação). Deixe 0 se não for prorrogação.",
                        verbose_name="Meses de Acréscimo",
                    ),
                ),
                (
                    "valor_acrescimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor adicional em R$ (apenas para aditivos de valor ou reequilíbrio). Deixe 0 se não for aditivo de valor.",
                        max_digits=15,
                        verbose_name="Valor de Acréscimo",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateField(
                        help_text="Data de assinatura do termo aditivo",
                        verbose_name="Data de Assinatura",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        help_text="Justificativa para o termo aditivo",
                        verbose_name="Justificativa",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        help_text="Contrato ao qual o termo aditivo se refere",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termos_aditivos",
                        to="contracts.contratopublico",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo Aditivo",
                "verbose_name_plural": "Termos Aditivos",
                "ordering": ["-data_assinatura"],
                "unique_together": {("contrato", "numero_termo")},
            },
        ),
    ]
