# Generated by Django 5.2.1 on 2025-11-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0028_projetopublico_remove_tarefa_centro_custo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("execucao", "Em Execução"),
                    ("finalizada", "Finalizada"),
                    ("faturada", "Faturada"),
                ],
                default="aberta",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
