# Generated by Django 5.2.1 on 2025-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0029_alter_sprint_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="horas_planejadas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total de horas planejadas para a OS (igual à quantidade total da OS)",
                max_digits=6,
                verbose_name="Horas Planejadas",
            ),
        ),
    ]
