# Generated by Django 5.2.1 on 2025-11-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0030_alter_ordemservico_horas_planejadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="hora_inicio_prevista",
            field=models.TimeField(
                default="09:00:00", verbose_name="Hora de Início Planejado"
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="hora_termino_prevista",
            field=models.TimeField(
                default="19:00:00", verbose_name="Hora de Término Planejado"
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_inicio_prevista",
            field=models.DateField(verbose_name="Data de Início Planejado"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_inicio_real",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Data/Hora de Início Real",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_termino_prevista",
            field=models.DateField(
                help_text="Não pode ser maior que a data de fim da sprint",
                verbose_name="Data de Término Planejado",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_termino_real",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Data/Hora de Término Real",
            ),
        ),
    ]
