# Generated by Django 5.2.1 on 2025-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0031_tarefa_hora_inicio_prevista_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="hora_inicio_prevista",
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="hora_termino_prevista",
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_inicio_prevista",
            field=models.DateTimeField(verbose_name="Data/Hora de Início Planejado"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_termino_prevista",
            field=models.DateTimeField(
                help_text="Não pode ser maior que a data de fim da sprint",
                verbose_name="Data/Hora de Término Planejado",
            ),
        ),
    ]
