# Generated by Django 5.2.1 on 2025-11-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0032_remove_tarefa_hora_inicio_prevista_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentohora",
            name="faturavel",
            field=models.BooleanField(default=True, verbose_name="Faturável"),
        ),
        migrations.AlterField(
            model_name="lancamentohora",
            name="tarefa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lancamentos_horas",
                to="contracts.tarefa",
                verbose_name="Tarefa",
            ),
        ),
    ]
