# Generated by Django 5.2.1 on 2025-11-26 14:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0033_add_faturavel_to_lancamentohora"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contratopublico",
            name="projeto",
        ),
        migrations.AlterField(
            model_name="termoaditivo",
            name="contrato",
            field=models.ForeignKey(
                help_text="Contrato ao qual o termo aditivo se refere",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="termos_aditivos",
                to="contracts.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="objeto",
            field=models.TextField(
                blank=True,
                help_text="Descrição do objeto do contrato",
                null=True,
                verbose_name="Objeto do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="regime_legal",
            field=models.CharField(
                choices=[
                    ("LEI_14133", "Lei 14.133/2021 (Licitações e Contratos)"),
                    (
                        "LEI_13303",
                        "Lei 13.303/2016 (Estatuto Jurídico da Empresa Pública)",
                    ),
                    ("PRIVADO", "Contrato Privado"),
                ],
                default="PRIVADO",
                help_text="Regime legal aplicável ao contrato",
                max_length=20,
                verbose_name="Regime Legal",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="valor_inicial",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor inicial do contrato em R$",
                max_digits=15,
                verbose_name="Valor Inicial",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_assinatura",
            field=models.DateField(verbose_name="Data de Assinatura/Início"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_fim",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Data de Fim"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="vigencia",
            field=models.IntegerField(
                choices=[
                    (12, "12 meses"),
                    (24, "24 meses"),
                    (36, "36 meses"),
                    (48, "48 meses"),
                    (60, "60 meses"),
                    (120, "120 meses"),
                ],
                verbose_name="Vigência Original (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="termoaditivo",
            name="justificativa",
            field=models.TextField(
                blank=True,
                help_text="Justificativa para o termo aditivo",
                null=True,
                verbose_name="Justificativa",
            ),
        ),
        migrations.AlterField(
            model_name="termoaditivo",
            name="meses_acrescimo",
            field=models.IntegerField(
                default=0,
                help_text="Meses adicionais de vigência (apenas para prorrogação)",
                verbose_name="Meses de Acréscimo",
            ),
        ),
        migrations.AlterField(
            model_name="termoaditivo",
            name="valor_acrescimo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor adicional em R$ (apenas para aditivos de valor ou reequilíbrio)",
                max_digits=15,
                verbose_name="Valor de Acréscimo",
            ),
        ),
        migrations.DeleteModel(
            name="ProjetoPublico",
        ),
        migrations.DeleteModel(
            name="ContratoPublico",
        ),
    ]
