# Generated by Django 5.2.1 on 2025-11-27 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0034_unificar_contratos_publicos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Documento"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("edital", "Edital de Licitação"),
                            ("etp", "Estudo Técnico Preliminar (ETP)"),
                            ("tr", "Termo de Referência (TR)"),
                            ("arp", "Ata de Registro de Preços (ARP)"),
                            ("proposta", "Proposta Comercial"),
                            ("outro", "Outro Documento"),
                        ],
                        default="contrato",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos_contratos/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Extraído"
                    ),
                ),
                (
                    "dados_extraidos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados Extraídos pela IA"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de Análise"),
                            ("processando", "Processando"),
                            ("analisado", "Analisado"),
                            ("erro", "Erro na Análise"),
                            ("revisado", "Revisado pelo Usuário"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_origem",
                        to="contracts.cliente",
                        verbose_name="Cliente Gerado",
                    ),
                ),
                (
                    "contrato_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_origem",
                        to="contracts.contrato",
                        verbose_name="Contrato Gerado",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Contrato",
                "verbose_name_plural": "Documentos de Contratos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
