# Generated by Django 5.2.1 on 2025-11-28 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0018_alter_itemcontrato_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resumo_contrato",
                    models.TextField(
                        help_text="Resumo executivo do contrato gerado pela IA",
                        verbose_name="Resumo do Contrato",
                    ),
                ),
                (
                    "pontos_atencao",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de pontos críticos identificados",
                        verbose_name="Pontos de Atenção",
                    ),
                ),
                (
                    "processo_execucao",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Etapas do processo de execução do contrato",
                        verbose_name="Processo de Execução",
                    ),
                ),
                (
                    "data_inicio_prevista",
                    models.DateField(verbose_name="Data de Início Prevista"),
                ),
                (
                    "data_fim_prevista",
                    models.DateField(verbose_name="Data de Fim Prevista"),
                ),
                (
                    "cronograma_detalhado",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cronograma com marcos e entregas",
                        verbose_name="Cronograma Detalhado",
                    ),
                ),
                (
                    "plano_comunicacao",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estrutura de comunicação e stakeholders",
                        verbose_name="Plano de Comunicação",
                    ),
                ),
                (
                    "template_status_report",
                    models.TextField(
                        blank=True,
                        help_text="Template para relatórios de status",
                        null=True,
                        verbose_name="Template de Status Report",
                    ),
                ),
                (
                    "frequencia_status_report",
                    models.CharField(
                        default="semanal",
                        help_text="Ex: semanal, quinzenal, mensal",
                        max_length=50,
                        verbose_name="Frequência do Status Report",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("pendente_aprovacao", "Pendente de Aprovação"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("em_execucao", "Em Execução"),
                            ("concluido", "Concluído"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "observacoes_aprovacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações da Aprovação"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_aprovados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plano_trabalho",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                # Campo 'projeto' será adicionado na migração 0060 após a criação do modelo Projeto
            ],
            options={
                "verbose_name": "Plano de Trabalho",
                "verbose_name_plural": "Planos de Trabalho",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="SLAImportante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome do SLA")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "tempo_resposta_horas",
                    models.IntegerField(verbose_name="Tempo de Resposta (horas)"),
                ),
                (
                    "tempo_solucao_horas",
                    models.IntegerField(verbose_name="Tempo de Solução (horas)"),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "alerta_antes_horas",
                    models.IntegerField(
                        default=24,
                        help_text="Horas antes do prazo para enviar alerta",
                        verbose_name="Alerta Antes (horas)",
                    ),
                ),
                (
                    "alerta_ativo",
                    models.BooleanField(default=True, verbose_name="Alerta Ativo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slas_importantes",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                # Campo 'sla' será adicionado na migração 0060 após a criação do modelo SLA
            ],
            options={
                "verbose_name": "SLA Importante",
                "verbose_name_plural": "SLAs Importantes",
                "ordering": ["prioridade", "tempo_resposta_horas"],
            },
        ),
    ]
