# Generated by Django 5.2.1 on 2025-11-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0036_add_plano_trabalho"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClausulaCritica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "numero_clausula",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número da Cláusula",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico"),
                            ("alto", "Alto"),
                            ("medio", "Médio"),
                        ],
                        default="medio",
                        max_length=20,
                        verbose_name="Impacto",
                    ),
                ),
                (
                    "acao_necessaria",
                    models.TextField(
                        help_text="Ações que devem ser tomadas para cumprir ou mitigar riscos",
                        verbose_name="Ação Necessária",
                    ),
                ),
                (
                    "prazo_atencao",
                    models.DateField(
                        blank=True,
                        help_text="Data limite para tomar ação",
                        null=True,
                        verbose_name="Prazo para Atenção",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clausulas_criticas",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cláusula Crítica",
                "verbose_name_plural": "Cláusulas Críticas",
                "ordering": ["impacto", "prazo_atencao"],
            },
        ),
        migrations.CreateModel(
            name="MatrizRACI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade",
                    models.CharField(max_length=255, verbose_name="Atividade"),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        help_text="Quem executa a atividade",
                        max_length=50,
                        null=True,
                        verbose_name="Responsável (R)",
                    ),
                ),
                (
                    "aprovador",
                    models.CharField(
                        blank=True,
                        help_text="Quem aprova a atividade",
                        max_length=50,
                        null=True,
                        verbose_name="Aprovador (A)",
                    ),
                ),
                (
                    "consultado",
                    models.CharField(
                        blank=True,
                        help_text="Quem é consultado (separado por vírgula)",
                        max_length=255,
                        null=True,
                        verbose_name="Consultado (C)",
                    ),
                ),
                (
                    "informado",
                    models.CharField(
                        blank=True,
                        help_text="Quem é informado (separado por vírgula)",
                        max_length=255,
                        null=True,
                        verbose_name="Informado (I)",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("planejamento", "Planejamento"),
                            ("implantacao", "Implantação"),
                            ("execucao", "Execução"),
                            ("suporte", "Suporte/Sustentação"),
                        ],
                        max_length=50,
                        verbose_name="Fase",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriz_raci",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz RACI",
                "verbose_name_plural": "Matriz RACI",
                "ordering": ["fase", "atividade"],
            },
        ),
        migrations.CreateModel(
            name="QuadroPenalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("penalizacao", "Penalização"),
                            ("glosa", "Glosa"),
                            ("multa", "Multa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentual aplicado sobre o valor do contrato/item",
                        max_digits=5,
                        null=True,
                        verbose_name="Percentual (%)",
                    ),
                ),
                (
                    "valor_fixo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor fixo em R$ (opcional)",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Fixo (R$)",
                    ),
                ),
                (
                    "condicao_aplicacao",
                    models.TextField(
                        help_text="Descrição de quando esta penalização/glosa se aplica",
                        verbose_name="Condição de Aplicação",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sla_importante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalizacoes",
                        to="contracts.slaimportante",
                        verbose_name="SLA Importante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quadro de Penalização/Glosa",
                "verbose_name_plural": "Quadros de Penalizações/Glosas",
            },
        ),
    ]
