# Generated by Django 5.2.1 on 2025-11-28 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_add_plano_trabalho_expandido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentocontrato",
            options={
                "ordering": ["analise", "tipo_documento", "nome"],
                "verbose_name": "Documento de Contrato",
                "verbose_name_plural": "Documentos de Contratos",
            },
        ),
        migrations.RemoveField(
            model_name="documentocontrato",
            name="cliente_gerado",
        ),
        migrations.RemoveField(
            model_name="documentocontrato",
            name="contrato_gerado",
        ),
        migrations.RemoveField(
            model_name="documentocontrato",
            name="criado_por",
        ),
        migrations.RemoveField(
            model_name="documentocontrato",
            name="dados_extraidos",
        ),
        migrations.AlterField(
            model_name="documentocontrato",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente de Análise"),
                    ("processando", "Processando"),
                    ("analisado", "Analisado"),
                    ("erro", "Erro na Análise"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="documentocontrato",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("contrato", "Contrato"),
                    ("edital", "Edital de Licitação"),
                    ("etp", "Estudo Técnico Preliminar (ETP)"),
                    ("tr", "Termo de Referência (TR)"),
                    ("arp", "Ata de Registro de Preços (ARP)"),
                    ("proposta", "Proposta Comercial"),
                    ("termo_aditivo", "Termo Aditivo"),
                    ("outro", "Outro Documento"),
                ],
                default="contrato",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.CreateModel(
            name="AnaliseContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Análise Contrato 009/2025 - CNPQ",
                        max_length=255,
                        verbose_name="Nome da Análise",
                    ),
                ),
                (
                    "texto_consolidado",
                    models.TextField(
                        blank=True,
                        help_text="Texto extraído de todos os documentos combinados",
                        null=True,
                        verbose_name="Texto Consolidado",
                    ),
                ),
                (
                    "dados_extraidos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados Extraídos pela IA"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de Análise"),
                            ("processando", "Processando"),
                            ("analisado", "Analisado"),
                            ("erro", "Erro na Análise"),
                            ("revisado", "Revisado pelo Usuário"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analises_origem",
                        to="contracts.cliente",
                        verbose_name="Cliente Gerado/Vinculado",
                    ),
                ),
                (
                    "contrato_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analises_origem",
                        to="contracts.contrato",
                        verbose_name="Contrato Gerado/Vinculado",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise de Contrato",
                "verbose_name_plural": "Análises de Contratos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="documentocontrato",
            name="analise",
            field=models.ForeignKey(
                blank=True,
                help_text="Análise à qual este documento pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="contracts.analisecontrato",
                verbose_name="Análise",
            ),
        ),
    ]
