# Generated by Django 5.2.1 on 2025-11-28 16:07

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0038_add_analise_contrato_multiplos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentocontrato",
            name="arquivo",
            field=models.FileField(
                max_length=500,
                upload_to=contracts.models.documento_contrato_upload_to,
                verbose_name="Arquivo",
            ),
        ),
    ]
