# Generated by Django 5.2.1 on 2025-11-28 16:07
# Corrigido: Migração vazia - o DocumentoContrato não existe no estado das migrações
# As alterações já foram aplicadas diretamente no banco de dados

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0038_add_analise_contrato_multiplos"),
    ]

    operations = [
        # Migração vazia - o campo arquivo do DocumentoContrato já está correto no banco
        # Esta migração existe apenas para manter a sequência de migrações
        # O modelo DocumentoContrato não foi criado via migração, então não podemos
        # usar operações de migração que dependem do estado do modelo
    ]
