# Generated by Django 5.2.1 on 2025-12-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0039_alter_documentocontrato_arquivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamacao",
            name="ordem_servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamacoes",
                to="contracts.ordemservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddField(
            model_name="reclamacao",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamacoes",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.AddField(
            model_name="reclamacao",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamacoes",
                to="contracts.sprint",
                verbose_name="Sprint",
            ),
        ),
        migrations.CreateModel(
            name="FeedbackSprintOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_contato", "Em Contato"),
                            ("respondido", "Respondido"),
                            ("convertido_oportunidade", "Convertido em Oportunidade"),
                            ("convertido_reclamacao", "Convertido em Reclamação"),
                        ],
                        default="pendente",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "satisfacao",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Muito Insatisfeito"),
                            (2, "Insatisfeito"),
                            (3, "Neutro"),
                            (4, "Satisfeito"),
                            (5, "Muito Satisfeito"),
                        ],
                        null=True,
                        verbose_name="Satisfação (1-5)",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comentários do Cliente"
                    ),
                ),
                (
                    "pontos_positivos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Pontos Positivos"
                    ),
                ),
                (
                    "pontos_melhoria",
                    models.TextField(
                        blank=True, null=True, verbose_name="Pontos de Melhoria"
                    ),
                ),
                (
                    "data_contato",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Contato"
                    ),
                ),
                (
                    "data_resposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Resposta"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Internas"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_sprint_os",
                        to="contracts.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_sprint_os",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "gerente_sucessos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks_gerenciados",
                        to="contracts.colaborador",
                        verbose_name="Gerente de Customer Success",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="contracts.ordemservico",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_sprint_os",
                        to="contracts.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="contracts.sprint",
                        verbose_name="Sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback de Sprint/OS",
                "verbose_name_plural": "Feedbacks de Sprint/OS",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="reclamacao",
            name="feedback_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reclamacoes_geradas",
                to="contracts.feedbacksprintos",
                verbose_name="Feedback de Origem",
            ),
        ),
    ]
