# Generated by Django 5.2.1 on 2025-12-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0040_add_etapas_feedback_cs"),
    ]

    operations = [
        # Nota: Operações do modelo 'oportunidade' removidas
        # O modelo será removido na migração 0050, então não faz sentido adicionar campos aqui
        # Se o modelo existir no banco, essas alterações já foram aplicadas diretamente
    ]
