# Generated by Django 5.2.1 on 2025-12-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0041_add_feedback_origem_oportunidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacksprintos",
            name="oportunidade_gerada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks_origem",
                to="contracts.oportunidade",
                verbose_name="Oportunidade Gerada",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="reclamacao_gerada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks_origem",
                to="contracts.reclamacao",
                verbose_name="Reclamação Gerada",
            ),
        ),
    ]
