# Generated by Django 5.2.1 on 2025-12-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0041_add_feedback_origem_oportunidade"),
    ]

    operations = [
        # Nota: Operações removidas - os modelos 'oportunidade' e 'reclamacao' serão removidos na migração 0050
        # Se os modelos existirem no banco, essas alterações já foram aplicadas diretamente
    ]
