# Generated by Django 5.2.1 on 2025-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0042_add_oportunidade_reclamacao_gerada_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbacksprintos",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Ticket de Contato - Customer Success",
                "verbose_name_plural": "Tickets de Contato - Customer Success",
            },
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="comentarios",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="oportunidade_gerada",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="pontos_melhoria",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="pontos_positivos",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="reclamacao_gerada",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="satisfacao",
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="elogios_criticas",
            field=models.TextField(
                blank=True,
                help_text="Compartilhe elogios, críticas ou sugestões de melhoria",
                null=True,
                verbose_name="Elogios ou Críticas",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="motivador_contato",
            field=models.CharField(
                choices=[
                    ("voluntario_cs", "Contato Voluntário do CS"),
                    ("solicitacao_comercial", "Por Solicitação da Área Comercial"),
                    (
                        "feedback_servico",
                        "Obter Feedback do Serviço Prestado (Automático)",
                    ),
                ],
                default="feedback_servico",
                max_length=30,
                verbose_name="Motivador do Contato",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_1_nota",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Totalmente Insatisfeito"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5 - Totalmente Satisfeito"),
                ],
                help_text="Avalie a qualidade do serviço prestado (0-5)",
                null=True,
                verbose_name="Pergunta 1: Qualidade do Serviço Prestado",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_2_nota",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Totalmente Insatisfeito"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5 - Totalmente Satisfeito"),
                ],
                help_text="Avalie o cumprimento dos prazos estabelecidos (0-5)",
                null=True,
                verbose_name="Pergunta 2: Cumprimento de Prazos",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_3_nota",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Totalmente Insatisfeito"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5 - Totalmente Satisfeito"),
                ],
                help_text="Avalie a comunicação e o atendimento recebido (0-5)",
                null=True,
                verbose_name="Pergunta 3: Comunicação e Atendimento",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente de Contato"),
                    ("em_contato", "Em Contato"),
                    ("respondido", "Feedback Recebido"),
                    ("concluido", "Concluído"),
                ],
                default="pendente",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
