# Generated by Django 5.2.1 on 2025-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0043_atualizar_feedback_ticket_nps"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacksprintos",
            name="numero_ticket",
            field=models.CharField(
                blank=True,
                help_text="Número único identificador do ticket",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Número do Ticket",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="motivador_contato",
            field=models.CharField(
                choices=[
                    ("voluntario_cs", "Contato Proativo"),
                    ("solicitacao_comercial", "Contato Reativo"),
                    (
                        "feedback_servico",
                        "Obter Feedback do Serviço Prestado (Automático)",
                    ),
                ],
                default="feedback_servico",
                max_length=30,
                verbose_name="Motivador do Contato",
            ),
        ),
    ]
