# Generated by Django 5.2.1 on 2025-12-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0044_adicionar_numero_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="pergunta_1_nota",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, qual a probabilidade de você recomendar nossos serviços? (0-10)",
                null=True,
                verbose_name="Pergunta 1: Qualidade do Serviço Prestado",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="pergunta_2_nota",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia o cumprimento dos prazos estabelecidos? (0-10)",
                null=True,
                verbose_name="Pergunta 2: Cumprimento de Prazos",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="pergunta_3_nota",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia a comunicação e o atendimento recebido? (0-10)",
                null=True,
                verbose_name="Pergunta 3: Comunicação e Atendimento",
            ),
        ),
    ]
