# Generated by Django 5.2.1 on 2025-12-05 22:04

from django.db import migrations, models


def migrar_dados_perguntas(apps, schema_editor):
    """Migra dados das perguntas antigas para as novas"""
    FeedbackSprintOS = apps.get_model('contracts', 'FeedbackSprintOS')
    
    for feedback in FeedbackSprintOS.objects.all():
        # Migrar pergunta_1_nota para pergunta_nps (pergunta principal)
        if feedback.pergunta_1_nota is not None:
            feedback.pergunta_nps = feedback.pergunta_1_nota
        
        # Migrar pergunta_2_nota para pergunta_satisfacao_prazos
        if feedback.pergunta_2_nota is not None:
            feedback.pergunta_satisfacao_prazos = feedback.pergunta_2_nota
        
        # Migrar pergunta_3_nota para pergunta_satisfacao_comunicacao
        if feedback.pergunta_3_nota is not None:
            feedback.pergunta_satisfacao_comunicacao = feedback.pergunta_3_nota
        
        # Se pergunta_1_nota não existir, usar a média das 3 perguntas para pergunta_nps
        if feedback.pergunta_nps is None:
            notas = []
            if feedback.pergunta_1_nota is not None:
                notas.append(feedback.pergunta_1_nota)
            if feedback.pergunta_2_nota is not None:
                notas.append(feedback.pergunta_2_nota)
            if feedback.pergunta_3_nota is not None:
                notas.append(feedback.pergunta_3_nota)
            
            if notas:
                # Usar a média arredondada como pergunta_nps
                media = round(sum(notas) / len(notas))
                feedback.pergunta_nps = min(10, max(0, media))  # Garantir que está entre 0-10
        
        feedback.save()


def reverter_migracao(apps, schema_editor):
    """Reverte a migração (não necessário, mas mantido para consistência)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0045_atualizar_escala_nps_0_10"),
    ]

    operations = [
        # Primeiro, adicionar os novos campos
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_nps",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, qual a probabilidade de você recomendar nossos serviços a um amigo ou colega? (0-10)",
                null=True,
                verbose_name="Pergunta NPS: Recomendação",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_satisfacao_comunicacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia a comunicação e o atendimento recebido? (0-10)",
                null=True,
                verbose_name="Satisfação: Comunicação e Atendimento",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_satisfacao_prazos",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia o cumprimento dos prazos estabelecidos? (0-10)",
                null=True,
                verbose_name="Satisfação: Cumprimento de Prazos",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="pergunta_satisfacao_qualidade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Improvável"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Provável"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia a qualidade do serviço prestado? (0-10)",
                null=True,
                verbose_name="Satisfação: Qualidade do Serviço",
            ),
        ),
        # Migrar dados
        migrations.RunPython(migrar_dados_perguntas, reverter_migracao),
        # Depois, remover os campos antigos
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="pergunta_1_nota",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="pergunta_2_nota",
        ),
        migrations.RemoveField(
            model_name="feedbacksprintos",
            name="pergunta_3_nota",
        ),
    ]
