# Generated by Django 5.2.1 on 2025-12-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0046_reestruturar_perguntas_nps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="pergunta_satisfacao_comunicacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Insatisfeito"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Satisfeito"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia a comunicação e o atendimento recebido? (0-10)",
                null=True,
                verbose_name="Satisfação: Comunicação e Atendimento",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="pergunta_satisfacao_prazos",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Insatisfeito"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Satisfeito"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia o cumprimento dos prazos estabelecidos? (0-10)",
                null=True,
                verbose_name="Satisfação: Cumprimento de Prazos",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacksprintos",
            name="pergunta_satisfacao_qualidade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "0 - Muito Insatisfeito"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10 - Muito Satisfeito"),
                ],
                help_text="Em uma escala de 0 a 10, como você avalia a qualidade do serviço prestado? (0-10)",
                null=True,
                verbose_name="Satisfação: Qualidade do Serviço",
            ),
        ),
    ]
