# Generated by Django 5.2.1 on 2025-12-05 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0047_atualizar_escala_satisfacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContatoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "funcao",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Função"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar como contato principal do cliente",
                        verbose_name="Contato Principal",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos",
                        to="contracts.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato do Cliente",
                "verbose_name_plural": "Contatos do Cliente",
                "ordering": ["-principal", "nome"],
            },
        ),
    ]
