# Generated by Django 5.2.1 on 2025-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0048_contatocliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cargo_responsavel",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Cargo do Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email_contato",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail de Contato"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome_responsavel",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nome do Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone_contato",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone de Contato"
            ),
        ),
    ]
