# Generated by Django 5.2.1 on 2025-12-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0049_alter_cliente_cargo_responsavel_and_more"),
    ]

    operations = [
        # Nota: Operações de remoção de campos e DeleteModel removidas
        # Os modelos 'Lead', 'Oportunidade' e 'Reclamacao' não existem no estado das migrações
        # Se existirem no banco, serão deletados diretamente via SQL se necessário
        # Esta migração está vazia para manter a sequência
    ]
