# Generated by Django 5.2.1 on 2025-12-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0049_alter_cliente_cargo_responsavel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oportunidade",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="feedback_origem",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="gerente_comercial",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="ordem_servico",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="oportunidade",
            name="sprint",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="feedback_origem",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="gerente_sucessos",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="ordem_servico",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="reclamacao",
            name="sprint",
        ),
        migrations.DeleteModel(
            name="Lead",
        ),
        migrations.DeleteModel(
            name="Oportunidade",
        ),
        migrations.DeleteModel(
            name="Reclamacao",
        ),
    ]
