# Generated by Django 5.2.1 on 2025-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0050_remove_lead_oportunidade_reclamacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="origem_contrato",
            field=models.CharField(
                choices=[
                    ("LIC_14133_PROPRIA", "Licitação própria (Lei 14.133)"),
                    (
                        "ARP_GERENCIADOR",
                        "Ata de Registro de Preços – órgão gerenciador",
                    ),
                    (
                        "ARP_PARTICIPANTE",
                        "Ata de Registro de Preços – órgão participante",
                    ),
                    ("ARP_ADESAO_CARONA", "Adesão tardia (carona) a ARP"),
                    ("DISPENSA_14133", "Dispensa de licitação (Lei 14.133)"),
                    (
                        "INEXIGIBILIDADE_14133",
                        "Inexigibilidade de licitação (Lei 14.133)",
                    ),
                    ("LIC_13303_PROPRIA", "Licitação própria (Lei 13.303)"),
                    ("CONTR_ESTATAL_DIRETA", "Contratação direta (Lei 13.303)"),
                    ("RFP_PRIVADA", "RFP (setor privado)"),
                    ("RFQ_PRIVADA", "Cotação / RFQ (setor privado)"),
                    ("NEGOCIACAO_DIRETA_PRIVADA", "Negociação direta (setor privado)"),
                    ("FRAMEWORK_PRIVADO", "Contrato derivado de Master/Framework"),
                    ("OUTRO", "Outro"),
                ],
                default="RFP_PRIVADA",
                help_text="Identifica se o contrato veio de licitação própria, ARP, RFP, dispensa, inexigibilidade, etc.",
                max_length=40,
                verbose_name="Origem do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="origem_contrato_confianca_ia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Score de confiança da IA para a origem identificada (0–1, ex: 0.85).",
                max_digits=5,
                null=True,
                verbose_name="Confiança da Origem (IA)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="origem_contrato_detalhe",
            field=models.CharField(
                blank=True,
                help_text="Informações complementares sobre a origem (ex: nº do edital, fundamento legal específico, descrição livre).",
                max_length=255,
                null=True,
                verbose_name="Detalhe da Origem (opcional)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="origem_contrato_justificativa_ia",
            field=models.TextField(
                blank=True,
                help_text="Resumo gerado pela IA explicando por que esta origem foi identificada.",
                null=True,
                verbose_name="Justificativa da Origem (IA)",
            ),
        ),
    ]
