# Generated by Django 5.2.1 on 2025-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0051_contrato_origem_contrato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="modalidade_licitacao",
            field=models.CharField(
                blank=True,
                help_text="Ex: Pregão Eletrônico, Tomada de Preços, Concorrência, Dispensa, Inexigibilidade",
                max_length=100,
                null=True,
                verbose_name="Modalidade de Licitação",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="numero_edital",
            field=models.CharField(
                blank=True,
                help_text="Número do edital de licitação",
                max_length=100,
                null=True,
                verbose_name="Número do Edital",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="numero_rfp_rfq",
            field=models.CharField(
                blank=True,
                help_text="Número do RFP (Request for Proposal) ou RFQ (Request for Quotation)",
                max_length=100,
                null=True,
                verbose_name="Número do RFP/RFQ",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="orgao_gerenciador_arp",
            field=models.CharField(
                blank=True,
                help_text="Nome do órgão que gerenciou a Ata de Registro de Preços",
                max_length=255,
                null=True,
                verbose_name="Órgão Gerenciador da ARP",
            ),
        ),
    ]
