# Generated by Django 5.2.1 on 2025-12-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0052_adicionar_campos_licitacao_arp_rfp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemfornecimento",
            name="item_fornecedor",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="item_fornecedor",
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="faturamento_separado",
            field=models.BooleanField(
                default=False,
                help_text="Se habilitado, permite fracionar o valor em NF-e (HW) e NFS-e (SW)",
                verbose_name="Faturamento Separado (HW/SW)",
            ),
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="valor_hw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor para faturamento como produto (NF-e)",
                max_digits=14,
                null=True,
                verbose_name="Valor HW (NF-e)",
            ),
        ),
        migrations.AddField(
            model_name="ordemfornecimento",
            name="valor_sw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor para faturamento como serviço (NFS-e)",
                max_digits=14,
                null=True,
                verbose_name="Valor SW (NFS-e)",
            ),
        ),
        migrations.AlterField(
            model_name="itemcontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("equipamento_hw", "Equipamento (somente HW)"),
                    ("equipamento_sw_embarcado", "Equipamento com SW embarcado"),
                    ("licenca_software", "Licença de Software"),
                    ("subscricao_software", "Subscrição de Software"),
                    ("solucao", "Solução"),
                    ("servico", "Serviço"),
                    ("treinamento", "Treinamento"),
                ],
                max_length=30,
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AlterField(
            model_name="itemfornecedor",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("equipamento_hw", "Equipamento (somente HW)"),
                    ("equipamento_sw_embarcado", "Equipamento com SW embarcado"),
                    ("licenca_software", "Licença de Software"),
                    ("subscricao_software", "Subscrição de Software"),
                    ("solucao", "Solução"),
                    ("servico", "Serviço"),
                    ("treinamento", "Treinamento"),
                ],
                max_length=30,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="ordemfornecimento",
            name="item_contrato",
            field=models.ForeignKey(
                limit_choices_to={
                    "tipo__in": [
                        "equipamento_hw",
                        "equipamento_sw_embarcado",
                        "licenca_software",
                        "subscricao_software",
                        "solucao",
                        "treinamento",
                    ]
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.itemcontrato",
                verbose_name="Item do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="ordemfornecimento",
            name="quantidade",
            field=models.PositiveIntegerField(verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="ordemfornecimento",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Valor Total"
            ),
        ),
        migrations.AlterField(
            model_name="ordemfornecimento",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_contrato",
            field=models.ForeignKey(
                limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.itemcontrato",
                verbose_name="Item do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_fornecedor_consultor",
            field=models.ForeignKey(
                blank=True,
                help_text="Item de fornecedor vinculado às horas do consultor",
                limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_consultor",
                to="contracts.itemfornecedor",
                verbose_name="Item de Fornecedor (Consultor)",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_fornecedor_gerente",
            field=models.ForeignKey(
                blank=True,
                help_text="Item de fornecedor vinculado às horas do gerente",
                limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_gerente",
                to="contracts.itemfornecedor",
                verbose_name="Item de Fornecedor (Gerente)",
            ),
        ),
        migrations.CreateModel(
            name="ItemFornecedorOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição do item",
                        verbose_name="Ordem",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "item_fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.itemfornecedor",
                        verbose_name="Item de Fornecedor",
                    ),
                ),
                (
                    "ordem_fornecimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_fornecedor",
                        to="contracts.ordemfornecimento",
                        verbose_name="Ordem de Fornecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Fornecedor da OF",
                "verbose_name_plural": "Itens de Fornecedor da OF",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItemFornecedorOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Unitário"
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição do item",
                        verbose_name="Ordem",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "item_fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.itemfornecedor",
                        verbose_name="Item de Fornecedor",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_fornecedor",
                        to="contracts.ordemservico",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Fornecedor da OS",
                "verbose_name_plural": "Itens de Fornecedor da OS",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
