# Generated by Django 5.2.1 on 2025-12-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0053_atualizar_tipos_itens_of_os"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemfornecimento",
            name="numero_of",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Número da OF",
            ),
        ),
    ]
