# Generated by Django 5.2.1 on 2025-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0054_tornar_numero_of_automatico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="situacao",
            field=models.CharField(
                blank=True,
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
    ]
