# Generated by Django 5.2.1 on 2025-12-16 18:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0055_tornar_situacao_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="valor_inicial",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="Valor inicial do contrato em R$ (calculado automaticamente)",
                max_digits=15,
                verbose_name="Valor Inicial",
            ),
        ),
    ]
