# Generated by Django 5.2.1 on 2025-12-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0056_calcular_valor_inicial_automatico"),
    ]

    operations = []
