# Generated by Django 5.2.1 on 2025-12-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0057_reestruturar_plano_trabalho_projeto_backlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backlog",
            options={
                "ordering": ["-prioridade", "-criado_em"],
                "verbose_name": "Backlog",
                "verbose_name_plural": "Backlogs",
            },
        ),
        migrations.RemoveField(
            model_name="backlog",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="planotrabalho",
            name="contrato",
        ),
        migrations.AddField(
            model_name="backlog",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                help_text="Contrato ao qual o backlog pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backlogs",
                to="contracts.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada do backlog",
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("critica", "Crítica"),
                ],
                default="media",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("convertido_projeto", "Convertido em Projeto"),
                    ("arquivado", "Arquivado"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="Título ou descrição do backlog",
                max_length=255,
                null=True,
                verbose_name="Título",
            ),
        ),
        migrations.AddField(
            model_name="planotrabalho",
            name="fornecedor",
            field=models.CharField(
                blank=True,
                help_text="Fornecedor principal do projeto (para definir modelo de exportação)",
                max_length=100,
                null=True,
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="backlog_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Backlog que originou este projeto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos_gerados",
                to="contracts.backlog",
                verbose_name="Backlog de Origem",
            ),
        ),
        migrations.AlterField(
            model_name="planotrabalho",
            name="projeto",
            field=models.OneToOneField(
                blank=True,
                help_text="Projeto ao qual o plano de trabalho pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plano_trabalho",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="contrato",
            field=models.ForeignKey(
                help_text="Contrato ao qual o projeto pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="contracts.contrato",
                verbose_name="Contrato",
            ),
        ),
    ]
