# Generated by Django 5.2.1 on 2025-12-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0057_reestruturar_plano_trabalho_projeto_backlog"),
    ]

    operations = [
        # Nota: Todas as operações removidas
        # Os modelos 'backlog', 'projeto' e 'planotrabalho' não existem no estado das migrações
        # (não foram criados via migração)
        # Se existirem no banco, essas alterações já foram aplicadas diretamente
        # Esta migração está vazia para manter a sequência
    ]
