# Generated by Django 5.2.1 on 2025-12-18 19:09

import contracts.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0058_alter_backlog_options_remove_backlog_projeto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome do Centro de Custo"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único do centro de custo",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["nome"],
            },
        ),
        migrations.RemoveField(
            model_name="planotrabalho",
            name="contrato",
        ),
        migrations.AddField(
            model_name="contrato",
            name="objeto",
            field=models.TextField(
                blank=True,
                help_text="Descrição do objeto do contrato",
                null=True,
                verbose_name="Objeto do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="regime_legal",
            field=models.CharField(
                choices=[
                    ("LEI_14133", "Lei 14.133/2021 (Licitações e Contratos)"),
                    (
                        "LEI_13303",
                        "Lei 13.303/2016 (Estatuto Jurídico da Empresa Pública)",
                    ),
                    ("PRIVADO", "Contrato Privado"),
                ],
                default="PRIVADO",
                help_text="Regime legal aplicável ao contrato",
                max_length=20,
                verbose_name="Regime Legal",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="horas_planejadas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total de horas planejadas para a OS (igual à quantidade total da OS)",
                max_digits=6,
                verbose_name="Horas Planejadas",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="horas_realizadas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total de horas realizadas (calculado automaticamente das tarefas)",
                max_digits=6,
                verbose_name="Horas Realizadas",
            ),
        ),
        migrations.AddField(
            model_name="planotrabalho",
            name="fornecedor",
            field=models.CharField(
                blank=True,
                help_text="Fornecedor principal do projeto (para definir modelo de exportação)",
                max_length=100,
                null=True,
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_assinatura",
            field=models.DateField(verbose_name="Data de Assinatura/Início"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_fim",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="Data de Fim"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="vigencia",
            field=models.IntegerField(
                choices=[
                    (12, "12 meses"),
                    (24, "24 meses"),
                    (36, "36 meses"),
                    (48, "48 meses"),
                    (60, "60 meses"),
                    (120, "120 meses"),
                ],
                verbose_name="Vigência Original (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="numero_os",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Backlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título ou descrição do backlog",
                        max_length=255,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do backlog",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_analise", "Em Análise"),
                            ("convertido_projeto", "Convertido em Projeto"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contrato ao qual o backlog pertence",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlogs",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backlog",
                "verbose_name_plural": "Backlogs",
                "ordering": ["-prioridade", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaborador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="gerente_comercial",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"cargo__icontains": "comercial"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_comercial",
                to="contracts.colaborador",
                verbose_name="Gerente Comercial da Conta",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="gerente_sucessos",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"cargo__icontains": "sucessos"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_sucessos",
                to="contracts.colaborador",
                verbose_name="Gerente de Sucessos",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="gerente_contrato",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"cargo__icontains": "gerente"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_gerenciados",
                to="contracts.colaborador",
                verbose_name="Gerente do Contrato",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Documento"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("edital", "Edital de Licitação"),
                            ("etp", "Estudo Técnico Preliminar (ETP)"),
                            ("tr", "Termo de Referência (TR)"),
                            ("arp", "Ata de Registro de Preços (ARP)"),
                            ("proposta", "Proposta Comercial"),
                            ("termo_aditivo", "Termo Aditivo"),
                            ("outro", "Outro Documento"),
                        ],
                        default="contrato",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        max_length=500,
                        upload_to=contracts.models.documento_contrato_upload_to,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Extraído"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de Análise"),
                            ("processando", "Processando"),
                            ("analisado", "Analisado"),
                            ("erro", "Erro na Análise"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "analise",
                    models.ForeignKey(
                        blank=True,
                        help_text="Análise à qual este documento pertence",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="contracts.analisecontrato",
                        verbose_name="Análise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Contrato",
                "verbose_name_plural": "Documentos de Contratos",
                "ordering": ["analise", "tipo_documento", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Projeto"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejamento", "Planejamento"),
                            ("em_andamento", "Em Andamento"),
                            ("pausado", "Pausado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejamento",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(editable=False, verbose_name="Data de Início"),
                ),
                (
                    "data_fim_prevista",
                    models.DateField(
                        editable=False, verbose_name="Data de Fim Prevista"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "backlog_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Backlog que originou este projeto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_gerados",
                        to="contracts.backlog",
                        verbose_name="Backlog de Origem",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        help_text="Contrato ao qual o projeto pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "gerente_projeto",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"cargo__icontains": "gerente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_gerenciados",
                        to="contracts.colaborador",
                        verbose_name="Gerente de Projeto",
                    ),
                ),
                (
                    "item_contrato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item do contrato vinculado ao projeto (apenas Serviço ou Treinamento)",
                        limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos",
                        to="contracts.itemcontrato",
                        verbose_name="Item do Contrato",
                    ),
                ),
                (
                    "ordem_servico",
                    models.OneToOneField(
                        blank=True,
                        help_text="OS vinculada ao projeto (criada automaticamente)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projeto",
                        to="contracts.ordemservico",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AlterField(
            model_name="planotrabalho",
            name="projeto",
            field=models.OneToOneField(
                blank=True,
                help_text="Projeto ao qual o plano de trabalho pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plano_trabalho",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do SLA"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("disponibilidade", "Disponibilidade"),
                            ("tempo_resposta", "Tempo de Resposta"),
                            ("resolucao", "Tempo de Resolução"),
                            ("atendimento", "Atendimento"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de SLA",
                    ),
                ),
                (
                    "meta",
                    models.CharField(
                        help_text="Ex: 99.9% de disponibilidade, 4 horas de resposta",
                        max_length=100,
                        verbose_name="Meta",
                    ),
                ),
                (
                    "valor_penalidade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor da Penalidade (R$)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slas",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA",
                "verbose_name_plural": "SLAs",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome da Sprint"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("execucao", "Em Execução"),
                            ("finalizada", "Finalizada"),
                            ("faturada", "Faturada"),
                        ],
                        default="aberta",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data de Fim")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="contracts.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Nome da Tarefa"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "bilhetar_na_os",
                    models.BooleanField(
                        default=True,
                        help_text="Se marcado, as horas desta tarefa serão contabilizadas na Ordem de Serviço do projeto",
                        verbose_name="Bilhetar na OS",
                    ),
                ),
                (
                    "status_sprint",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nao_iniciada", "Não Iniciada"),
                            ("em_execucao", "Em Execução"),
                            ("finalizada", "Finalizada"),
                        ],
                        help_text="Status quando a tarefa está em uma sprint",
                        max_length=20,
                        null=True,
                        verbose_name="Status (Sprint)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("pausada", "Pausada"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "data_inicio_prevista",
                    models.DateTimeField(verbose_name="Data/Hora de Início Planejado"),
                ),
                (
                    "data_termino_prevista",
                    models.DateTimeField(
                        help_text="Não pode ser maior que a data de fim da sprint",
                        verbose_name="Data/Hora de Término Planejado",
                    ),
                ),
                (
                    "data_inicio_real",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Data/Hora de Início Real",
                    ),
                ),
                (
                    "data_termino_real",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Data/Hora de Término Real",
                    ),
                ),
                (
                    "horas_planejadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Horas Planejadas",
                    ),
                ),
                (
                    "horas_consumidas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Calculado automaticamente baseado em lançamentos de horas",
                        max_digits=6,
                        verbose_name="Horas Consumidas",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "backlog",
                    models.ForeignKey(
                        blank=True,
                        help_text="Backlog do contrato que originou esta tarefa (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="contracts.backlog",
                        verbose_name="Backlog de Origem",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        help_text="Projeto ao qual a tarefa pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="contracts.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultor Técnico ou Gerente de Projetos",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="contracts.colaborador",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sprint à qual a tarefa está atribuída (se None, fica no backlog do projeto)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas",
                        to="contracts.sprint",
                        verbose_name="Sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoHora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Início")),
                ("hora_termino", models.TimeField(verbose_name="Hora de Término")),
                (
                    "horas_trabalhadas",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        verbose_name="Horas Trabalhadas",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Trabalho"
                    ),
                ),
                (
                    "faturavel",
                    models.BooleanField(default=True, verbose_name="Faturável"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos_horas",
                        to="contracts.colaborador",
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos_horas",
                        to="contracts.tarefa",
                        verbose_name="Tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento de Hora",
                "verbose_name_plural": "Lançamentos de Horas",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TermoAditivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_termo",
                    models.CharField(
                        help_text="Número oficial do termo aditivo",
                        max_length=100,
                        verbose_name="Número do Termo Aditivo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRORROGACAO", "Prorrogação"),
                            ("VALOR", "Aditivo de Valor"),
                            ("REEQUILIBRIO", "Reequilíbrio Econômico-Financeiro"),
                        ],
                        help_text="Tipo de termo aditivo",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "meses_acrescimo",
                    models.IntegerField(
                        default=0,
                        help_text="Meses adicionais de vigência (apenas para prorrogação)",
                        verbose_name="Meses de Acréscimo",
                    ),
                ),
                (
                    "valor_acrescimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor adicional em R$ (apenas para aditivos de valor ou reequilíbrio)",
                        max_digits=15,
                        verbose_name="Valor de Acréscimo",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateField(
                        help_text="Data de assinatura do termo aditivo",
                        verbose_name="Data de Assinatura",
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True,
                        help_text="Justificativa para o termo aditivo",
                        null=True,
                        verbose_name="Justificativa",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        help_text="Contrato ao qual o termo aditivo se refere",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termos_aditivos",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo Aditivo",
                "verbose_name_plural": "Termos Aditivos",
                "ordering": ["-data_assinatura"],
                "unique_together": {("contrato", "numero_termo")},
            },
        ),
    ]
