# Generated by Django 5.2.1 on 2025-12-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0059_criar_modelos_faltantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacksprintos",
            name="gerente_sucessos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks_gerenciados",
                to="contracts.colaborador",
                verbose_name="Gerente de Customer Success",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="ordem_servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="contracts.ordemservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks_sprint_os",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.AddField(
            model_name="feedbacksprintos",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="contracts.sprint",
                verbose_name="Sprint",
            ),
        ),
        migrations.AddField(
            model_name="slaimportante",
            name="sla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slas_importantes",
                to="contracts.sla",
                verbose_name="SLA Vinculado",
            ),
        ),
    ]
