# Generated by Django 5.2.1 on 2025-12-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0060_adicionar_referencias_modelos"),
    ]

    operations = [
        migrations.AddField(
            model_name="planotrabalho",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planos_trabalho",
                to="contracts.projeto",
                verbose_name="Projeto Gerado",
            ),
        ),
    ]
