# Generated by Django 5.2.1 on 2025-12-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0061_adicionar_projeto_plano_trabalho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planotrabalho",
            name="projeto",
            field=models.OneToOneField(
                blank=True,
                help_text="Projeto ao qual o plano de trabalho pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plano_trabalho",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
    ]
