# Generated by Django 5.2.1 on 2025-12-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0062_alter_planotrabalho_projeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="ordem_servico",
            field=models.OneToOneField(
                blank=True,
                help_text="OS vinculada ao projeto (criada automaticamente)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projeto",
                to="contracts.ordemservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
    ]
