# Generated by Django 5.2.1 on 2025-12-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0063_adicionar_ordem_servico_projeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="projeto",
            field=models.ForeignKey(
                help_text="Projeto ao qual a tarefa pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
    ]
