# Generated by Django 5.2.1 on 2025-12-18 19:35

from django.db import migrations, models


def associar_tarefas_a_projetos(apps, schema_editor):
    """Associa tarefas sem projeto a projetos existentes através de sprint ou backlog"""
    Tarefa = apps.get_model('contracts', 'Tarefa')
    Projeto = apps.get_model('contracts', 'Projeto')
    Contrato = apps.get_model('contracts', 'Contrato')
    
    tarefas_sem_projeto = Tarefa.objects.filter(projeto__isnull=True)
    
    for tarefa in tarefas_sem_projeto:
        projeto_associado = None
        
        # Tentar associar através da sprint
        if tarefa.sprint and hasattr(tarefa.sprint, 'projeto') and tarefa.sprint.projeto:
            projeto_associado = tarefa.sprint.projeto
        # Tentar associar através do backlog
        elif tarefa.backlog and hasattr(tarefa.backlog, 'contrato') and tarefa.backlog.contrato:
            # Buscar o primeiro projeto do contrato
            projeto_associado = Projeto.objects.filter(contrato=tarefa.backlog.contrato).first()
        
        if projeto_associado:
            tarefa.projeto = projeto_associado
            tarefa.save()
        else:
            # Se não houver como associar, deletar a tarefa
            tarefa.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0064_adicionar_projeto_tarefa"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="bilhetar_na_os",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, as horas desta tarefa serão contabilizadas na Ordem de Serviço do projeto",
                verbose_name="Bilhetar na OS",
            ),
        ),
        # Primeiro associar tarefas a projetos antes de tornar o campo obrigatório
        migrations.RunPython(associar_tarefas_a_projetos, migrations.RunPython.noop),
    ]
