# Generated by Django 5.2.1 on 2025-12-18 23:06

from django.db import migrations


def copiar_bilhetavel_para_bilhetar(apps, schema_editor):
    """Copia valores de bilhetavel_os para bilhetar_na_os se necessário"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Verificar se o campo bilhetavel_os existe antes de tentar copiar
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'contracts_tarefa' 
            AND column_name = 'bilhetavel_os'
        """)
        if cursor.fetchone():
            # Copiar valores de bilhetavel_os para bilhetar_na_os
            cursor.execute("""
                UPDATE contracts_tarefa 
                SET bilhetar_na_os = bilhetavel_os 
                WHERE bilhetar_na_os IS NULL OR bilhetar_na_os != bilhetavel_os
            """)


def reverse_copiar(apps, schema_editor):
    """Operação reversa (não necessária, mas mantida para consistência)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0066_tornar_projeto_obrigatorio_tarefa"),
    ]

    operations = [
        migrations.RunPython(copiar_bilhetavel_para_bilhetar, reverse_copiar),
        # Remover campo bilhetavel_os diretamente do banco (não existe no estado de migração)
        migrations.RunSQL(
            sql="ALTER TABLE contracts_tarefa DROP COLUMN IF EXISTS bilhetavel_os;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
