# Generated by Django 5.2.1 on 2025-12-23 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0068_adicionar_ordem_sprint_tarefa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={
                "ordering": ["ordem_sprint", "-criado_em"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
        migrations.AlterField(
            model_name="sprint",
            name="data_fim",
            field=models.DateField(verbose_name="Data de Término"),
        ),
        migrations.CreateModel(
            name="DiarioBordoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_registro",
                    models.CharField(
                        choices=[
                            ("analise_ia", "Análise Inicial (IA)"),
                            ("evento", "Evento"),
                            ("reuniao", "Reunião"),
                            ("comunicacao", "Comunicação"),
                            ("decisao", "Decisão"),
                            ("problema", "Problema"),
                            ("solucao", "Solução"),
                            ("mudanca", "Mudança"),
                            ("outro", "Outro"),
                        ],
                        default="analise_ia",
                        max_length=20,
                        verbose_name="Tipo de Registro",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo completo do registro do diário de bordo",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "resumo_geral",
                    models.TextField(
                        blank=True,
                        help_text="Resumo executivo do contrato",
                        null=True,
                        verbose_name="Resumo Geral",
                    ),
                ),
                (
                    "itens_mais_importantes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de itens críticos do contrato",
                        verbose_name="Itens Mais Importantes",
                    ),
                ),
                (
                    "operacionalizacao_equipe",
                    models.TextField(
                        blank=True,
                        help_text="Como o contrato deve ser operacionalizado",
                        null=True,
                        verbose_name="Operacionalização pela Equipe",
                    ),
                ),
                (
                    "informacoes_gerente_contrato_cs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações relevantes para gestão comercial e customer success",
                        verbose_name="Informações para Gerente de Contrato/CS",
                    ),
                ),
                (
                    "informacoes_gerente_projetos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informações técnicas para execução dos serviços",
                        verbose_name="Informações para Gerente de Projetos",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diario_bordo",
                        to="contracts.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_diario_bordo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro do Diário de Bordo",
                "verbose_name_plural": "Registros do Diário de Bordo",
                "ordering": ["-criado_em"],
            },
        ),
    ]
