# Generated by Django 5.2.1 on 2026-01-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0035_add_documento_contrato"),
        ("contracts", "0070_create_stakeholder_contrato"),
    ]

    operations = []
