# Generated by Django 5.2.1 on 2026-01-08 23:49

import contracts.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0071_merge_20260108_2011")]

    operations = [
        migrations.AlterModelOptions(
            name="backlog",
            options={
                "ordering": ["-prioridade", "-criado_em"],
                "verbose_name": "Backlog",
                "verbose_name_plural": "Backlogs",
            },
        ),
        migrations.AlterModelOptions(
            name="documentocontrato",
            options={
                "ordering": ["analise", "tipo_documento", "nome"],
                "verbose_name": "Documento de Contrato",
                "verbose_name_plural": "Documentos de Contratos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stakeholdercontrato",
            unique_together=set(),
        ),
        # COMENTADO: Campo não existe no banco de dados
        #         migrations.RemoveField(
        #             model_name="documentocontrato",
        #             name="cliente_gerado",
        #         ),
        # COMENTADO: Campo não existe no banco de dados
        #         migrations.RemoveField(
        #             model_name="documentocontrato",
        #             name="contrato_gerado",
        #         ),
        # COMENTADO: Campo não existe no banco de dados
        #         migrations.RemoveField(
        #             model_name="documentocontrato",
        #             name="criado_por",
        #         ),
        # COMENTADO: Campo não existe no banco de dados
        #         migrations.RemoveField(
        #             model_name="documentocontrato",
        #             name="dados_extraidos",
        #         ),
        migrations.AddField(
            model_name="backlog",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                help_text="Contrato ao qual o backlog pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backlogs",
                to="contracts.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada do backlog",
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("critica", "Crítica")],
                default="media",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_analise", "Em Análise"),
                    ("convertido_projeto", "Convertido em Projeto"),
                    ("arquivado", "Arquivado")],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="backlog",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="Título ou descrição do backlog",
                max_length=255,
                null=True,
                verbose_name="Título",
            ),
        ),
        migrations.AddField(
            model_name="documentocontrato",
            name="analise",
            field=models.ForeignKey(
                blank=True,
                help_text="Análise à qual este documento pertence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="contracts.analisecontrato",
                verbose_name="Análise",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                help_text="Projeto ao qual a OS está vinculada",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens_servico",
                to="contracts.projeto",
                verbose_name="Projeto",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="backlog_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Backlog que originou este projeto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos_gerados",
                to="contracts.backlog",
                verbose_name="Backlog de Origem",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="item_contrato",
            field=models.ForeignKey(
                blank=True,
                help_text="Item do contrato vinculado ao projeto (apenas Serviço ou Treinamento)",
                limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos",
                to="contracts.itemcontrato",
                verbose_name="Item do Contrato",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdercontrato",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail do membro da equipe técnica (usado quando tipo = Equipe Técnica)",
                max_length=254,
                null=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdercontrato",
            name="nome",
            field=models.CharField(
                blank=True,
                help_text="Nome do membro da equipe técnica (usado quando tipo = Equipe Técnica)",
                max_length=255,
                null=True,
                verbose_name="Nome",
            ),
        ),
        migrations.AddField(
            model_name="stakeholdercontrato",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Telefone do membro da equipe técnica (usado quando tipo = Equipe Técnica)",
                max_length=20,
                null=True,
                verbose_name="Telefone",
            ),
        ),
        # COMENTADO: Campo bilhetar_na_os já existe no banco de dados
        # migrations.AddField(
        #     model_name="tarefa",
        #     name="bilhetavel_os",
        #     field=models.BooleanField(
        #         default=True,
        #         help_text="Se marcado, as horas desta tarefa serão contabilizadas na OS do projeto",
        #         verbose_name="Bilhetável na OS",
        #     ),
        # ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_inicial",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="Valor inicial do contrato em R$ (calculado automaticamente)",
                max_digits=15,
                verbose_name="Valor Inicial",
            ),
        ),
        migrations.AlterField(
            model_name="documentocontrato",
            name="arquivo",
            field=models.FileField(
                max_length=500,
                upload_to=contracts.models.documento_contrato_upload_to,
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="documentocontrato",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente de Análise"),
                    ("processando", "Processando"),
                    ("analisado", "Analisado"),
                    ("erro", "Erro na Análise")],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="documentocontrato",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("contrato", "Contrato"),
                    ("edital", "Edital de Licitação"),
                    ("etp", "Estudo Técnico Preliminar (ETP)"),
                    ("tr", "Termo de Referência (TR)"),
                    ("arp", "Ata de Registro de Preços (ARP)"),
                    ("proposta", "Proposta Comercial"),
                    ("termo_aditivo", "Termo Aditivo"),
                    ("outro", "Outro Documento")],
                default="contrato",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_fornecedor_consultor",
            field=models.ForeignKey(
                blank=True,
                help_text="Item de fornecedor vinculado às horas do consultor",
                limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_consultor",
                to="contracts.itemfornecedor",
                verbose_name="Item de Fornecedor (Consultor)",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="item_fornecedor_gerente",
            field=models.ForeignKey(
                blank=True,
                help_text="Item de fornecedor vinculado às horas do gerente",
                limit_choices_to={"tipo__in": ["servico", "treinamento"]},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="os_gerente",
                to="contracts.itemfornecedor",
                verbose_name="Item de Fornecedor (Gerente)",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="contrato",
            field=models.ForeignKey(
                help_text="Contrato ao qual o projeto pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="contracts.contrato",
                verbose_name="Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholdercontrato",
            name="papel",
            field=models.CharField(
                help_text="Papel do stakeholder no contrato",
                max_length=50,
                verbose_name="Papel/Função",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholdercontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CONTRATADA", "Contratada"),
                    ("CONTRATANTE", "Contratante"),
                    ("EQUIPE_TECNICA", "Equipe Técnica")],
                max_length=20,
                verbose_name="Tipo de Stakeholder",
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="ordem_servico",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: vincular a uma OS para horas faturadas (vinculada ao projeto)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to="contracts.ordemservico",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.DeleteModel(
            name="DiarioBordoContrato",
        ),
    ]
